# Generated by Django 3.1.7 on 2021-05-13 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notes', '0002_notescomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notescomments',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Notes.notes'),
        ),
        migrations.AlterField(
            model_name='notescomments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NoteComment', to=settings.AUTH_USER_MODEL),
        ),
    ]
