# Generated by Django 3.1.7 on 2021-05-11 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notes', '0001_initial'),
        ('Sites', '0002_sites_topic'),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GroupCreator', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='GroupMembers', to=settings.AUTH_USER_MODEL)),
                ('notes', models.ManyToManyField(blank=True, related_name='GroupNotes', to='Notes.Notes')),
                ('sites', models.ManyToManyField(blank=True, related_name='GroupSites', to='Sites.Sites')),
                ('videos', models.ManyToManyField(blank=True, related_name='GroupVideos', to='Videos.Videos')),
            ],
        ),
    ]
