# Generated by Django 3.1.7 on 2021-05-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20210511_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='UserGroups', to='Profile.Groups'),
        ),
    ]
