# Generated by Django 3.1.7 on 2021-05-12 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0003_profile_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupComents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.groups')),
                ('user', models.ManyToManyField(related_name='GroupCommentUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
