# Generated by Django 3.1.7 on 2021-05-12 10:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0004_groupcoments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupComents',
            new_name='GroupComments',
        ),
    ]
