# Generated by Django 3.1.7 on 2021-05-12 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0005_auto_20210512_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcomments',
            name='user',
        ),
        migrations.AddField(
            model_name='groupcomments',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='GroupCommentUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
