# Generated by Django 3.1.7 on 2021-05-10 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
        ('Sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.topic'),
        ),
    ]
