# Generated by Django 3.1.7 on 2021-05-13 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
        ('Sites', '0002_sites_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='topic',
        ),
        migrations.AddField(
            model_name='sites',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.subject'),
        ),
    ]
