# Generated by Django 3.1.7 on 2021-05-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sites', '0004_sitescomments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SitesComments',
        ),
    ]
