# Generated by Django 3.1.7 on 2021-05-31 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0003_videoscomments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideosComments',
        ),
    ]
