# Generated by Django 3.1.7 on 2021-05-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
