# Generated by Django 3.1.7 on 2021-05-31 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_subject_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
